# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Seeking your face
subtitle: 寻求智慧和真理
description:
author: xin wang
language: zh-Hans  #语言，中文
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.mrxin.wang
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 100
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: next

baidu_url_submit:
  count: 1 ## 提交最新的一个链接
  host: mrxin.wang ## 在百度站长平台中注册的域名
  token: wmxbzjQuv5KUUL4M ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: https://github.com/mojia/mojia.github.io.git
  branch: master
- type: baidu_url_submitter ## 这是新加的


# hexo-admin authentification
admin:
  username: mojia
  password_hash: $2a$10$yGMVMyHdi8IHfkfo/xJ6RuaPmffN9T/kT5Nk2CoKhLuY2c15P9cri
  secret: my super secret 


# add post views
leancloud_visitors:
  enable: true
  app_id: LvRtybubpk55rrfjiOkF5EL0-gzGzoHsz
  app_key: F1YCeYtkOehddvyCvGyPWEs3
